import '../models/seudo.dart';

class AntoModel {
  List<SeudoModel> seuModel = [
    SeudoModel(1, "lento", {
      'detenido': false,
      'fuerte': false,
      'rápido': true,
      'alto': false,
    }),
    SeudoModel(2, 'valiante', {
      'grande': false,
      'seguro': false,
      'cobarde': true,
      'fuerte': false,
    }),
    SeudoModel(3, "triste", {
      'alegre': true,
      'llorón': false,
      'preocupado': false,
      'aburrido': false,
    }),
    SeudoModel(4, "abrir", {
      'subir': false,
      'cerrar': true,
      'entrar': false,
      'liberar': false,
    }),
    SeudoModel(5, "limpio", {
      'pulcro': false,
      'sucio': true,
      'brillante': false,
      'lavado': false,
    }),
    SeudoModel(6, "nuevo", {
      'viejo': true,
      'recien': false,
      'mediano': false,
      'alto': false,
    }),
    SeudoModel(7, "agradable", {
      'desagradable': true,
      'simpático': false,
      'fuerte': false,
      'listo': false,
    }),
    SeudoModel(8, "inicio", {
      'comienzo': false,
      'fin': true,
      'principio': false,
      'salida': false,
    }),
    SeudoModel(9, "si", {
      'aceptar': false,
      'no': true,
      'decir': false,
      'yo': false,
    }),
    SeudoModel(10, "ganador", {
      'vencedor': false,
      'perdedor': true,
      'primero': false,
      'fuerte': false,
    }),
    SeudoModel(11, "seco", {
      'caliente': false,
      'mojado': true,
      'exprimido': false,
      'ventilado': false,
    }),
    SeudoModel(12, "grande", {
      'inmenso': false,
      'enorme': false,
      'chico': true,
      'mediano': false,
    }),
    SeudoModel(13, "blanco", {
      'pálido': false,
      'rosa': false,
      'negro': true,
      'color': false,
    }),
    SeudoModel(14, "fácil", {
      'rápido': false,
      'veloz': false,
      'dificil': true,
      'bien': false,
    }),
    SeudoModel(15, "divertido", {
      'chistoso': false,
      'entretenido': false,
      'llamativo': false,
      'aburrido': true,
    }),
    SeudoModel(16, "caliente", {
      'tibio': false,
      'frío': true,
      'caloroso': false,
      'arde': false,
    }),
    SeudoModel(17, "siempre", {
      'fecuentemente': false,
      'nunca': true,
      'diario': false,
      'hoy': false,
    }),
    SeudoModel(18, "salir", {
      'subir': false,
      'encontrar': true,
      'caminar': false,
      'entrar': false,
    }),
    SeudoModel(19, "sentarse", {
      'acostarse': false,
      'recostarse': false,
      'dormido': false,
      'pararse': true,
    }),
    SeudoModel(20, "bueno", {
      'gracioso': false,
      'triste': false,
      'negro': false,
      'malo': true,
    }),
    SeudoModel(21, "verdad", {
      'cierto': false,
      'honesto': false,
      'mentira': true,
      'si': false,
    }),
    SeudoModel(22, "reír", {
      'cantar': false,
      'llorar': true,
      'nadar': false,
      'jugar': false,
    }),
    SeudoModel(23, "silencio", {
      'callado': false,
      'apagado': false,
      'tenue': false,
      'ruido': true,
    }),
    SeudoModel(24, "bajo", {
      'alto': true,
      'pequeño': false,
      'corto': false,
      'chico': false,
    }),
    SeudoModel(25, "liquido", {
      'aguado': false,
      'fluido': false,
      'sólido': false,
      'ágil': false,
    }),
    SeudoModel(25, "preocupar", {
      'ansioso': false,
      'triste': false,
      'tranquilizar': true,
      'nervioso': false,
    }),
    SeudoModel(26, "alejarse", {
      'acercarse': true,
      'irse': false,
      'retractarse': false,
      'salir': false,
    }),
    SeudoModel(27, "afirmación", {
      'positivo': false,
      'negación': true,
      'aceptar': false,
      'si': false,
    }),
    SeudoModel(28, "hablar", {
      'decir': false,
      'opinar': false,
      'callar': true,
      'cantar': false,
    }),
    SeudoModel(29, "comprar", {
      'adquirir': false,
      'vender': true,
      'tener': false,
      'dar': false,
    }),
    SeudoModel(30, "útil", {
      'bueno': false,
      'inútil': true,
      'ocupado': false,
      'usado': false,
    }),
  ];
}
