import '../models/orto.dart';

class OrotModel {
  List<OrtModel> seuModel = [
    OrtModel(1, {
      'istoria': false,
      'historia': true,
      'hiztoria': false,
      'hystoria': false,
    }),
    OrtModel(2, {
      'divujo': false,
      'divuguo': false,
      'dibujo': true,
      'dibugo': false,
    }),
    OrtModel(1, {
      'ciguiente': false,
      'siguiente': true,
      'sigiente': false,
      'siguente': false,
    }),
    OrtModel(1, {
      'bivos': false,
      'vivos': true,
      'bibos': false,
      'vibos': false,
    }),
    OrtModel(1, {
      'gúerra': false,
      'guera': false,
      'guerra': true,
      'juerra': false,
    }),
    OrtModel(1, {
      'biejo': false,
      'biego': false,
      'viego': false,
      'viejo': true,
    }),
    OrtModel(1, {
      'peses': false,
      'pezes': false,
      'peces': true,
      'peszes': false,
    }),
    OrtModel(1, {
      'yubia': false,
      'llubia': false,
      'lluvia': true,
      'yuvia': false,
    }),
    OrtModel(1, {
      'basura': true,
      'bacura': false,
      'vasura': false,
      'bazura': false,
    }),
    OrtModel(1, {
      'iglesia': true,
      'higlesia': false,
      'iglecia': false,
      'higlecia': false,
    }),
    OrtModel(1, {
      'abitar': false,
      'havitar': false,
      'habitar': true,
      'avitar': false,
    }),
    OrtModel(1, {
      'alcólicas': false,
      'alcohólicas': true,
      'alcóhlicas': false,
      'alcoholicas': false,
    }),
    OrtModel(1, {
      'ezpermatosoides': false,
      'ezpermatosoidesa': false,
      'espermatozoides': true,
      'espermatozooides': false,
    }),
    OrtModel(1, {
      'oceano': true,
      'oceani': false,
      'oseano': false,
      'océano': false,
    }),
    OrtModel(1, {
      'composisión': false,
      'compocision': false,
      'composición': true,
      'compocición': false,
    }),
    OrtModel(1, {
      'gente': true,
      'juente': false,
      'jente': false,
      'guente': false,
    }),
    OrtModel(1, {
      'exesos': false,
      'eccesos': false,
      'eoresos': false,
      'excesos': true,
    }),
    OrtModel(1, {
      'orisontal': false,
      'horizóntal': false,
      'orizontal': false,
      'horizontal': true,
    }),
    OrtModel(1, {
      'tristesa': false,
      'tristezah': false,
      'tristezha': false,
      'tristeza': true,
    }),
    OrtModel(1, {
      'ocsigeno': false,
      'occigeno': false,
      'oxijeno': false,
      'oxígeno': true,
    }),
    OrtModel(1, {
      'antigúa': false,
      'antigua': true,
      'antijua': false,
      'hantigua': false,
    }),
    OrtModel(1, {
      'cabayo': false,
      'cavallo': false,
      'caballo': true,
      'kaballo': false,
    }),
    OrtModel(1, {
      'selula': false,
      'celula': true,
      'zelula': false,
      'célula': false,
    }),
    OrtModel(1, {
      'vorregos': false,
      'boregos': false,
      'borregos': true,
      'borrejos': false,
    }),
    OrtModel(1, {
      'precidente': false,
      'prezidente': false,
      'presidente': true,
      'prescidente': false,
    }),
    OrtModel(1, {
      'población': false,
      'poblasion': false,
      'poblacion': true,
      'poblasión': false,
    }),
    OrtModel(1, {
      'averiguar': true,
      'aberiguar': false,
      'aberigúar': false,
      'aberigiar': false,
    }),
    OrtModel(1, {
      'guirafa': false,
      'girafa': false,
      'xirafa': false,
      'jirafa': true,
    }),
    OrtModel(1, {
      'rayo': true,
      'rrallo': false,
      'rallo': false,
      'rrayo': false,
    }),
    OrtModel(1, {
      'contaminasion': false,
      'contaminación': true,
      'contaminazion': false,
      'contaminasión': false,
    }),
    OrtModel(1, {
      'lexión': false,
      'leccion': false,
      'lexción': false,
      'lección': true,
    }),
    OrtModel(1, {
      'gestionar': true,
      'gestioner': false,
      'guestionar': false,
      'gilestionar': false,
    }),
    OrtModel(1, {
      'organizacion': false,
      'organización': true,
      'organisación': false,
      'orjanización': false,
    }),
    OrtModel(1, {
      'círculos': true,
      'sirculos': false,
      'církulos': false,
      'circulos': false,
    }),
    OrtModel(1, {
      'arbustos': true,
      'arrbustos': false,
      'arrvustos': false,
      'harbustos': false,
    }),
    OrtModel(1, {
      'energia': true,
      'enerjía': false,
      'energuía': false,
      'energía': false,
    }),
    OrtModel(1, {
      'nosivo': false,
      'nosibo': false,
      'nocibo': false,
      'nocivo': true,
    }),
  ];
}
