import '../models/seudo.dart';

class SeuModel {
  List<SeudoModel> seuModel = [
    SeudoModel(1, "yetallis", {
      'yetillas': false,
      'yetallis': true,
      'llistalle': false,
      'yitellas': false,
    }),
    SeudoModel(2, 'midajo', {
      'mijoda': false,
      'midajo': true,
      'dajomi': false,
      'molajo': false,
    }),
    SeudoModel(3, "naronla", {
      'nalaron': false,
      'lonaran': false,
      'naronla': true,
      'tarenla': false,
    }),
    SeudoModel(4, "cidallo", {
      'cidallo': true,
      'codalli': false,
      'cilloda': false,
      'cillado': false,
      'cidolla': false,
    }),
    SeudoModel(5, "posbillas", {
      'posbillas': true,
      'posllisba': false,
      'biposllas': false,
      'tarsbollas': false,
      'mesbilla': false,
    }),
    SeudoModel(6, "fesuro", {
      'feruso': false,
      'fesuro': true,
      'rosufe': false,
      'tesaro': false,
      'masaro': false,
    }),
    SeudoModel(7, "cemparvir", {
      'cempirvar': false,
      'parcemvir': false,
      'cemvarpir': false,
      'cemparvir': true,
      'pancevir': false,
    }),
    SeudoModel(8, "berrachó", {
      'chóberra': false,
      'becharró': false,
      'barrechó': true,
      'berrachó': false,
      'berrócha': false,
    }),
    SeudoModel(9, "corarze", {
      'zecorar': false,
      'cerorza': false,
      'corerza': false,
      'carorze': false,
      'corarze': true,
    }),
    SeudoModel(10, "bofalla", {
      'fabolla': false,
      'bollafa': false,
      'bofalla': true,
      'mafolla': false,
      'casolla': false,
    }),
    SeudoModel(11, "axomu", {
      'omuxa': false,
      'axumo': false,
      'amuxo': false,
      'axomu': true,
      'amoxu': false,
    }),
    SeudoModel(12, "chenize", {
      'chineze': false,
      'zeniche': false,
      'chezine': false,
      'chenize': true,
      'chezeni': false,
    }),
    SeudoModel(13, "troxemo", {
      'tromexo': false,
      'troxemo': true,
      'xotremo': false,
      'tromoxe': false,
      'trexomo': false,
    }),
    SeudoModel(14, "múltablo", {
      'túblomal': false,
      'múltobla': false,
      'mílbatlo': false,
      'núltablo': false,
      'múltablo': true,
    }),
    SeudoModel(15, "pulipro", {
      'pulipro': true,
      'puprilo': false,
      'putipro': false,
      'prupoli': false,
      'pulopri': false,
    }),
    SeudoModel(16, "llampoce", {
      'copellan': false,
      'lampoce': false,
      'llampeco': false,
      'llamcope': false,
      'llampoce': true,
    }),
    SeudoModel(17, "rúmado", {
      'rumabo': false,
      'modarú': false,
      'rúdano': false,
      'rúmado': true,
      'rúdamo': false,
    }),
    SeudoModel(18, "ritreación", {
      'ritreacióm': false,
      'ritreación': true,
      'ciónreatri': false,
      'riceatrión': false,
      'ritriocean': false,
    }),
    SeudoModel(19, "silueción", {
      'sileución': false,
      'sineuciol': false,
      'silueción': true,
      'siluación': false,
      'siluesión': false,
    }),
    SeudoModel(20, "ispuerzos", {
      'isporzues': false,
      'espuirzos': false,
      'izpuestor': false,
      'isbuerzos': false,
      'ispuerzos': true,
    }),
    SeudoModel(21, "pregonla", {
      'prelonga': false,
      'pregonla': true,
      'loganpre': false,
      'preganlo': false,
      'pregamlo': false,
    }),
    SeudoModel(22, "omtiner", {
      'omtenir': false,
      'omniter': false,
      'omtiner': true,
      'emtinor': false,
      'omliner': false,
    }),
    SeudoModel(23, "troblimas", {
      'troblamis': false,
      'troblinaz': false,
      'trobramis': false,
      'troblimas': true,
      'troblinas': false,
    }),
    SeudoModel(24, "oxpuesti", {
      'tuexpios': false,
      'oxbuesti': false,
      'oxpitues': false,
      'oxpuesti': true,
      'oxtuespi': false,
    }),
    SeudoModel(25, "mogares", {
      'morages': false,
      'mogeras': false,
      'maguares': false,
      'mogarres': false,
      'mogares': true,
    }),
    SeudoModel(25, "lásdime", {
      'lásdemi': false,
      'lásmide': false,
      'lásdime': true,
      'lásdine': false,
      'lázdime': false,
    }),
    SeudoModel(25, "rigrefo", {
      'rifrego': false,
      'rigreto': false,
      'rigrefo': true,
      'ritegro': false,
      'rrigreto': false,
    }),
    SeudoModel(25, "abnetos", {
      'abnetoz': false,
      'abtenos': false,
      'abnelos': false,
      'abnetos': true,
      'abnotes': false,
    }),
    SeudoModel(25, "hesporia", {
      'hesropia': false,
      'hesporria': false,
      'hesporia': true,
      'hespario': false,
      'hesboria': false,
    }),
    SeudoModel(25, "tragmanto", {
      'tragmanto': false,
      'tragtanmo': false,
      'tragmamto': true,
      'tragmonta': false,
      'trajmanto': false,
    }),
    SeudoModel(25, "trudieza", {
      'truzieda': false,
      'trudieza': false,
      'trubieza': true,
      'trudiesa': false,
      'trudiaze': false,
    }),
    SeudoModel(25, "petilles", {
      'petiles': false,
      'petellis': false,
      'petillespe': false,
      'petilles': true,
      'petiyes': false,
    }),
    SeudoModel(25, "obspura", {
      'obspura': true,
      'obsrupa': false,
      'obspurra': false,
      'obsqura': false,
      'obruspa': false,
    }),
  ];
}
