import '../models/seudo.dart';

class SinoModel {
  List<SeudoModel> seuModel = [
    SeudoModel(1, "ladrón", {
      'honesto': false,
      'perdido': false,
      'ratero': true,
      'víctima': false,
    }),
    SeudoModel(1, "cansado", {
      'ligero': false,
      'agotado': true,
      'arriba': false,
      'acostado': false,
    }),
    SeudoModel(1, "observar", {
      'oír': false,
      'tocar': false,
      'contar': false,
      'mirar': true,
    }),
    SeudoModel(1, "perdido", {
      'encantado': false,
      'vacilante': false,
      'extraviado': true,
      'atento': false,
    }),
    SeudoModel(1, "inteligente", {
      'atontado': false,
      'listo': true,
      'bueno': false,
      'deportista': false,
    }),
    SeudoModel(1, "contento", {
      'brincar': false,
      'triste': false,
      'alegre': true,
      'tranquilo': false,
    }),
    SeudoModel(1, "comida", {
      'zanahoria': false,
      'basura': false,
      'orgánico': false,
      'alimento': true,
    }),
    SeudoModel(1, "miedo", {
      'alegría': false,
      'temor': true,
      'compasión': false,
      'muela': false,
    }),
    SeudoModel(1, "suelo", {
      'pared': false,
      'cocina': false,
      'alfombra': false,
      'piso': true,
    }),
    SeudoModel(1, "estudiantes", {
      'niños': false,
      'maestros': false,
      'alumnos': true,
      'jóvenes': false,
    }),
    SeudoModel(1, "carro", {
      'bicicleta': false,
      'tractor': false,
      'camión': false,
      'coche': true,
    }),
    SeudoModel(1, "pelón", {
      'calvo': true,
      'limpio': false,
      'brillante': false,
      'peludo': false,
    }),
    SeudoModel(1, "presos", {
      'prisioneros': true,
      'bandidos': false,
      'perdidos': false,
      'asustados': false,
    }),
    SeudoModel(1, "mentiroso", {
      'farsante': true,
      'chistoso': false,
      'elocuente': false,
      'honesto': false,
    }),
    SeudoModel(1, "madre", {
      'tía': false,
      'progenitora': true,
      'señora': false,
      'mujer': false,
    }),
    SeudoModel(1, "país", {
      'estado': false,
      'nación': true,
      'bandera': false,
      'territorio': false,
    }),
    SeudoModel(1, "duro", {
      'fácil': false,
      'suave': false,
      'severo': true,
      'terciopelo': false,
    }),
    SeudoModel(1, "bonito", {
      'completo': false,
      'bondad': false,
      'feo': false,
      'lindo': true,
    }),
    SeudoModel(1, "diferente", {
      'igual': false,
      'parecido': false,
      'indiferente': false,
      'distinto': true,
    }),
    SeudoModel(1, "empezar", {
      'terminar': false,
      'comenzar': true,
      'mantener': false,
      'ir': false,
    }),
    SeudoModel(1, "furioso", {
      'enojado': true,
      'calmado': false,
      'apurado': false,
      'fuerte': false,
    }),
    SeudoModel(1, "grande", {
      'chico': false,
      'mediano': false,
      'rascacielos': false,
      'enorme': true,
    }),
    SeudoModel(1, "fácil", {
      'riesgoso': false,
      'sencillo': true,
      'difícil': false,
      'engorroso': false,
    }),
    SeudoModel(1, "sorprendida", {
      'cegado': false,
      'aburrido': false,
      'asombrado': true,
      'sorpresa': false,
    }),
    SeudoModel(1, "sabroso", {
      'desagradable': false,
      'delicioso': true,
      'insípido': false,
      'frío': false,
    }),
    SeudoModel(1, "maravilloso", {
      'cotidiano': false,
      'simple': false,
      'grandioso': true,
      'común': false,
    }),
    SeudoModel(1, "salón", {
      'patio': false,
      'jardín': false,
      'aula': true,
      'recámara': false,
    }),
    SeudoModel(1, "extremo", {
      'mediano': false,
      'línea': false,
      'límite': true,
      'centro': false,
    }),
    SeudoModel(1, "discusión", {
      'disputa': true,
      'coincidencia': false,
      'tratado': false,
      'acuerdo': false,
    }),
    SeudoModel(1, "casa", {
      'lugar': false,
      'escuela': false,
      'terreno': false,
      'hogar': true,
    }),
    SeudoModel(1, "chiste", {
      'fiesta': false,
      'celebración': false,
      'broma': true,
      'reírse': false,
    }),
    SeudoModel(1, "vagabundo", {
      'andariego': true,
      'sucio': false,
      'corredor': false,
      'trabajador': false,
    }),
    SeudoModel(1, "felicidad", {
      'emoción': false,
      'tristeza': false,
      'sentimiento': false,
      'alegría': true,
    }),
  ];
}
